### ISSUE TITLE
Inherits from...

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#1]
Are you sure you meant inherits from IConvertible?

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Category.cs#L10

**Comment by clarkj93** [comment]
This class originally did inherit from IConvertible, however I changed this before publishing to github but I forgot to remove the comment. Ignore this, I will remove the comment.
