### ISSUE TITLE
Not necessarily just not reviewed

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#10]
It will be reviewed records, accepted ones, rejected etc. as this automatic checking process could be checking and accepting faster than the hacked ones coming in.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/ReviewTools.cs#L39

**Comment by clarkj93** [comment]
This is now loaded into memory from the start of the check, to improve performance so this will only be done once per interval so I don't see this being an issue anymore.
