### ISSUE TITLE
For loop

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#11]
Try a `for (int i = 0; .....` loop here and see what the performance enhancement is, I would of hoped it would be better. You might want to use simulate a test here for 100,000 repeats just on some dummy code, not necessarily within this project, maybe use a test project for trying out some of these ideas.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/ReviewTools.cs#L121

Look for this occuring elsewhere in you code.

**Comment by clarkj93** [comment]
Now been replaced with `for(int i = 0; i < count;i++)` where applicable.
