### ISSUE TITLE
Added new reviewedfeedback

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#13]
I've added a new reviewfeedback which indicates it was a potential hack, called SuspectHack, value of 4.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/ReviewTools.cs#L50

**Comment by clarkj93** [comment]
Changed to:
`dat.UpdateData($"UPDATE synchronisation SET reviewedby = '{appName}', reviewed = SYSDATE(), reviewedstatus = 2, reviewedfeedback = 4 WHERE serverid IN ({tmper})");`

Note the variable name has been changed from Db to dat.
