### ISSUE TITLE
Using datatable as for loop

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#14]
You need to consider what you've done here a little more, have a look at the following page and consider justifying why you would put the fields into a list?

http://codedisplay.com/datatable-foreach-loop-to-read-records-c-vb-net-asp-net/

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/ReviewTools.cs#L44

This isn't the only place this is happening, you need to consider elsewhere as well.

**Comment by clarkj93** [comment]
This has been changed to the following and similar in all other occurrences:

 `           DataTable dt = db.GetDataTable("SELECT serverid FROM synchronisation WHERE reviewedstatus = 0");`
            

  `          if (dt.Rows.Count > limit) // ADD TIME COMPARISON HERE`
   `         {`
    `            string tmper = String.Empty;`
     `           foreach (DataRow x in dt.Rows) //foreach over each data row in the datatable`
      `          {`
       `             tmper += $"{x[0]},";`
                `}` 
`//..do some more stuff not relevant to this example`
`}`
