### ISSUE TITLE
Variable naming convention

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#15]
Very small point here but worth noting, you need to use camel case for variable naming inside methods.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/ReviewTools.cs#L68

Unfortunately for you I used to be responsible for code naming conventions in a few companies ;-)

Also this isn't the only one, you need to go through and check all.

**Comment by clarkj93** [comment]
Corrected to camel case.
