### ISSUE TITLE
Byte or HashTag checking

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#18]
This is one I'm not sure about, the HastTag is a much shorter byte array (I think 32 bytes) which is computated from the original lengthier byte array (in our case image), the HashTag will remain the same is the original image remains the same, if one bit is changed then the HashTag will change.

Anyway try a performance check, maybe using test project again, that checks the difference between using HashTag and byte by byte checking.

https://support.microsoft.com/en-us/help/307020/how-to-compute-and-compare-hash-values-by-using-visual-c

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/ReviewTools.cs#L164

**Comment by clarkj93** [comment]
I have constructed a small console app to test this with 2 very large 158mb .txt files containing a base64 string (the image originally produced somewhere close 1mb but I pasted it a few times in the same .txt file to get a better idea of performance difference).  Here are the log results:
` `
`Press any key to start..`
` `
` `
`Entire HashTag Method took 1307.0235 milliseconds`
` `
`HashTag Comparison took 0 milliseconds`
` `
` `
`Entire Base64 Method took 4280.9606 milliseconds`
` `
`Base64 Comparison took 437.4938 milliseconds`
` `
` `
`Press any key to restart..`
` `

The difference on this scale is quite large, although we will not be dealing with Base64 strings of this size or anywhere close I think it still needs changing. This will be updated by the end of the day.
