### ISSUE TITLE
Repeatedly calling parse function

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#2]
This is a performance question, parsing json is a time consuming process, try a different design so that you only parse the json once for the whole Category, not for each member.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Category.cs#L24

Consider using a similar technique for the Database.cs class, that is because the opening of a connection takes time.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Database.cs#L25

For both of the above changes I'd like you to consider using the following .NET object to test...
https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.aspx

**Comment by clarkj93** [comment]
JObject is now parse'd only once and the Database class is now disposable, specifying an open connection on creating the instance, and closing once the object is disposed. Runs successfully.
