### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#3]
I'm not sure about the result here but using the 1000 dummy records we discussed, instead of using a exception trap (below) which I think uses extra processing time as it is required to generate exception objects and log its position using StackTrace, try just checking for whether the member returns a null using an `if` statement and if not then use the value.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Category.cs#L26

**Comment by clarkj93** [comment]
These methods now check if the member is visible in the JObject first and return a value or null depending on the result.
