### ISSUE TITLE
App Settings...

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#4]
Not linked to a specific line, but this is how to store information in the App.Config and get it back out. This technique can also be used for ASP.NET as the web site does not allow the App.Config (think its called Web.Config on a web site) to be shown to any user browsing the site.

https://support.microsoft.com/en-us/help/815786/how-to-store-and-retrieve-custom-information-from-an-application-confi

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Program.cs#L18

**Comment by clarkj93** [comment]
See below Automatic Review.exe.config xml:

`<?xml version="1.0" encoding="utf-8"?>`
`<configuration>`
 `   <startup> `
  `      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />`
   ` </startup>`
    `<appSettings>`
     ` <add key="databaseConnectionString" value="server=localhost;uid=root;pwd=Q1819668;database=cancam" />`
      `<add key="intervalInSeconds" value="60" />`
      `<add key="packetLimit" value="10000" />`
      `<add key="version" value="v1.0" />`
`   </appSettings>`
`<system.data>`
 `   <DbProviderFactories>`
  `    <remove invariant="MySql.Data.MySqlClient" />`
   `   <add description=".Net Framework Data Provider for MySQL" invariant="MySql.Data.MySqlClient" name="MySQL Data Provider" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.10.4.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />`
    `</DbProviderFactories>`
`  </system.data></configuration>`
