### ISSUE TITLE
Base64 Decoding

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#5]
There is a framework method for that, which should also give you a performance enhancement.

`byte[] data = Convert.FromBase64String(encodedString);`

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Category.cs#L52

**Comment by clarkj93** [comment]
That gave an exception first time, however I've discovered that you need to convert it to a Base64 string prior to doing this and have result with the below:
`string tmp = Convert.ToBase64String(Encoding.UTF8.GetBytes(json[member].ToString()));`
 `               result = Convert.FromBase64String(tmp);`

**Comment by TycTak** [comment]
What exception did you get, there'll be an overhead for the ToBase64String so if we can cure it we should.

**Comment by clarkj93** [comment]
This has been altered to use a Hash byte array via ASCIIEncoder.
