### ISSUE TITLE
Convert Short classes

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#6]
Not sure what you were considering here, but now you've removed the Guardian class do you need these two method for Entity and POI?

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Category.cs#L73

**Comment by clarkj93** [comment]
I would argue yes. The Entity and the POI are both treated as a Category to ensure a generic process, then based on the Data.Categories enum the Category can be converted to a POI and Entity at the last minute, rather than tailor 2 methods for each type.

**Comment by TycTak** [comment]
Another option could be to use a generic type, but I'm not entirely sure what you mean here so maybe we should talk...

`public T To<T>()`
`{`
`    return new T(this.Json);`
`}`

**Comment by clarkj93** [comment]
It's not possible to return the correct class with a construct that takes a parameter. Alternatively it is possible to do this without a parameter but then the calling method would have to specify the json packet to be used to initialise the variables. It makes more sense and is a lot less code to have the individual To methods. The workaround is on the link below, however I don't think it is ideal for a class that currently only needs to be converted to 2 types

https://stackoverflow.com/questions/853703/how-to-constrain-generic-type-to-must-have-a-construtor-that-takes-certain-param

**Comment by clarkj93** [comment]
Changed to the following:
` `
`public T To<T>()`
 `       {`
  `          object result = null;`
` `
  `          if (typeof(T) == typeof(ShortEntity))`
   `                 result = new ShortEntity(json.ToString());`
    `        else if (typeof(T) == typeof(ShortPOI))`
     `           result = new ShortPOI(json.ToString());`
      `      else`
       `         result = this;`
` `
  `          return (T)result;`
   `     }`
