### ISSUE TITLE
Sending messages back to program

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#8]
Carrying on from our discussion last night, the following example shows a method of raising an event to a class which has subscribed as a handler. This means that its generic and you can you this in ASP.NET as well as in this project so the code is re-usable.

http://www.c-sharpcorner.com/uploadfile/Ashush/events-in-C-Sharp/

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/ReviewInitiator.cs#L26

**Comment by clarkj93** [comment]
I have added the delegate to the ReviewInitiator class and made the newMessage event static so on crating an instance of this class you specify the expression to be executed, this also means any other class in the .DLL can call the event. The ReviewIntiator class is now created as an instance like so:
`ReviewInitiator RI = new ReviewInitiator(interval, dbConnection);`
                 `   ReviewInitiator.newMessage += (x) => { Console.WriteLine($"{DateTime.Now} : {x}"); };`
                 `   RI.Start();`
