### ISSUE TITLE
Missed part of requirements

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#9]
I think you may of missed part of the requirements, page 2 of the project document, 4th section down starting "Profanity checking should check for..." states that you need to run a 2nd check against a list of correct words. I only see a list of BannedWords here.

https://github.com/clarkj93/Automatic-Review-Console/blob/38daf3946b9a8bfdf5a750790f4249db00e9728a/Automatic%20Review/Profanity.cs#L12

Don't forget the last thing you always do is go through project document and check off everything you should of done.

**Comment by clarkj93** [comment]
No need for 2 checks, we can find the difference between the 2 lists and only check the remaining banned words:

`    internal class Profanity //to filter out messages that need to be manual checked `
 `   {`
  `      private List<string> bannedWords { get; set; }`

 `       public Profanity(List<string> badWords, List<string> goodWords)`
  `      {`
   `         bannedWords = badWords;`

 `           foreach(string i in bannedWords)`
  `          {`
   `             foreach(string x in goodWords)`
    `            {`
     `               if (x.Contains(i))`
      `                  bannedWords.Remove(i);`
       `         }`
        `    }`
`        }`
`//other methods here`
`}`

**Comment by clarkj93** [comment]
The above is incorrect, I have changed the way the IsAcceptableString(string message) method checks for profanity. If a banned word is found it will then check the possibility of it being an allowed word. See the next commit tonight to view the changes, after testing this has proved successful.
